# Generated by Django 5.1.3 on 2025-05-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('guestCount', models.IntegerField()),
                ('reservationTime', models.DateTimeField(auto_now=True)),
                ('comments', models.CharField(max_length=1000)),
            ],
        ),
    ]
